version: '3.7'
services:
  mongodb:
    container_name: mongodb-conatiner
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    networks:
      - project
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db

  rest-api:
    container_name: node-docker-api
    depends_on:
      - mongodb
    restart: unless-stopped
    build:
      context: ./
    env_file: ./.env
    ports:
      - '$NODE_DOCKER_PORT:$NODE_DOCKER_PORT'
    networks:
      - project
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$NODE_DOCKER_PORT
    stdin_open: true
    tty: true

  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    depends_on:
      - rest-api
    networks:
      - project
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db:
  caddy_data:
  caddy_config:


networks:
  project:


